# add the following to _config.yml file
title: M. M. Akash
logo: assets/img/Cp-80162 copy.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
